Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 814, in callit 
    func(*args)
  File "g:\Seamoth\seamoth.py", line 137, in show_frames
    cv2image = cv2.cvtColor(self.frame,cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Traceback (most recent call last):
  File "g:\Seamoth\homebase.py", line 15, in <module>
    main()
  File "g:\Seamoth\homebase.py", line 12, in main
    ui.frame = seamoth.Camera.decode(conn.output)
  File "g:\Seamoth\seamoth.py", line 121, in decode
    return cv2.imdecode(numpy.asarray(bytearray(image, encoding="utf-8"), dtype="uint8"), cv2.IMREAD_COLOR)
KeyboardInterrupt