192.168.86.42
Exception in thread Thread-2:
Traceback (most recent call last):
192.168.86.42
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
Exception in Tkinter callback
    self.run()
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
TypeError: seamoth.DataConnection._listen() argument after * must be an iterable, not socket
Traceback (most recent call last):
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Miles Contopoulos\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "G:\Seamoth\seamoth.py", line 131, in show_frames
    cv2image = cv2.cvtColor(self.frame,cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'